# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 22:45
from __future__ import unicode_literals

import diary.models
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('image', models.ImageField(upload_to=diary.models.imageLocation)),
                ('imgType', models.CharField(choices=[('mni', 'Main Image'), ('gal', 'Gallery')], default='gal', max_length=3)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'dateCreated'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(editable=False)),
                ('text', models.TextField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateUpdated', models.DateField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Post')),
            ],
            options={
                'ordering': ['order', 'dateCreated'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Post'),
        ),
    ]
