# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
