# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
