# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20160321_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateCreated', 'order', 'title']},
        ),
    ]
