# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('diary', '0006_auto_20160321_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='diary.TaggedPost', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='taggedpost',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.Post'),
        ),
        migrations.AddField(
            model_name='taggedpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_taggedpost_items', to='taggit.Tag'),
        ),
    ]
