# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-20 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20170519_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateCreated', 'title']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='order',
        ),
    ]
