# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='date',
            new_name='dateAdquired',
        ),
        migrations.AddField(
            model_name='payment',
            name='dateSet',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('ONT', 'on time'), ('CMP', 'completed'), ('LAT', 'late')], default='ONT', max_length=3),
        ),
    ]
