# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20160402_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='compayName',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
