# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='Payment', max_length=140),
        ),
    ]
