# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-03 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import web_client.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ellugar.co', max_length=140)),
                ('default_description', models.CharField(default='description', max_length=140)),
                ('default_preview', models.ImageField(upload_to=web_client.models.imageLocation)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
