# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-21 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0005_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_subscription',
            field=models.TextField(default='subscribe'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mail',
            field=models.EmailField(default='afk@ellugar.co', max_length=254),
        ),
    ]
