# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_client', '0007_siteconfiguration_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='cv',
        ),
    ]
