# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-25 17:54
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion
import podcast.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('file_ogg', models.FileField(upload_to=podcast.models.audioLocation)),
                ('file_mp3', models.FileField(upload_to=podcast.models.audioLocation)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(editable=False)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to=podcast.models.imageLocation)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateUpdated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-dateCreated'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(editable=False)),
                ('text', models.TextField()),
                ('small_text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=podcast.models.imageLocation)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateUpdated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-dateCreated'],
            },
        ),
        migrations.CreateModel(
            name='TaggedPodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_taggedpodcast_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='podcast',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='podcast.TaggedPodcast', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast'),
        ),
    ]
