# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-25 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.CharField(default='Games', max_length=140),
            preserve_default=False,
        ),
    ]
