# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_podcast_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.CharField(default='AFK', max_length=140),
            preserve_default=False,
        ),
    ]
