# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_podcast_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='author_mail',
            field=models.EmailField(default='afk@ellugar.co', max_length=140),
            preserve_default=False,
        ),
    ]
