# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_podcast_author_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='category',
            new_name='child_category',
        ),
        migrations.AddField(
            model_name='podcast',
            name='parent_category',
            field=models.CharField(default='category', max_length=140),
            preserve_default=False,
        ),
    ]
