# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_podcast_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='file_ogg',
        ),
        migrations.AddField(
            model_name='episode',
            name='duration',
            field=models.DurationField(default='10'),
            preserve_default=False,
        ),
    ]
