# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_auto_20170525_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_size',
            field=models.CharField(default='10', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='audio_type',
            field=models.CharField(default='10', max_length=20),
            preserve_default=False,
        ),
    ]
