# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import podcast.models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_auto_20170525_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='file_mp3',
        ),
        migrations.AddField(
            model_name='episode',
            name='audio_mp3',
            field=models.FileField(default=1, upload_to=podcast.models.upload_to_episode_audio),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='audio_ogg',
            field=models.FileField(blank=True, upload_to=podcast.models.upload_to_episode_audio),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(upload_to=podcast.models.upload_to_episode_cover),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(upload_to=podcast.models.upload_to_podcast_cover),
        ),
    ]
