# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0010_podcast_itunesurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='dateCreated',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='dateUpdated',
            field=models.DateField(),
        ),
    ]
