# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0011_auto_20170530_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='dateCreated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='dateUpdated',
            field=models.DateField(auto_now=True),
        ),
    ]
