# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0012_auto_20170530_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='feedBurner',
            field=models.URLField(blank=True, null=True),
        ),
    ]
