# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 06:40
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0016_auto_20170615_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast'),
        ),
    ]
