# Generated by Django 2.0 on 2018-05-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0017_auto_20170615_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='episodesUrl',
            field=models.URLField(default='ellugar.co'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='website',
            field=models.URLField(default='ellugar.co'),
            preserve_default=False,
        ),
    ]
