# Generated by Django 2.0.5 on 2018-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0018_auto_20180514_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='googlePodcast',
            field=models.URLField(blank=True, null=True),
        ),
    ]
