# Generated by Django 2.0.5 on 2018-06-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0019_podcast_googlepodcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
