# Generated by Django 2.0.5 on 2018-06-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0021_auto_20180621_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
