# Generated by Django 2.0.5 on 2018-06-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0023_auto_20180621_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
    ]
