# Generated by Django 2.1.2 on 2018-10-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0025_auto_20180621_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='faq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
