# Generated by Django 2.1.2 on 2018-11-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0026_podcast_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
    ]
