# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-04 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0002_auto_20170904_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
