# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0003_auto_20170904_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-date_init']},
        ),
        migrations.RemoveField(
            model_name='city',
            name='date_final',
        ),
    ]
