# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0004_auto_20170905_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-dateCreated']},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='date_init',
            new_name='dateCreated',
        ),
    ]
