# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 20:04
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0005_auto_20170905_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('color', colorful.fields.RGBColorField(default='#ffffff')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='title',
        ),
    ]
