# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nomad', '0006_auto_20170926_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['order', 'slug']},
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nomad.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
