# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-19 17:22
from __future__ import unicode_literals

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_entry_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='entry',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Entry'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
