# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('image', models.ImageField(upload_to=portfolio.models.imageLocation)),
                ('imgType', models.CharField(choices=[('gal', 'Gallery')], default='gal', max_length=3)),
                ('order', models.PositiveIntegerField(default=0)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'dateCreated'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('image', models.ImageField(null=True, upload_to=portfolio.models.imageLocation)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('smallDescription', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=portfolio.models.imageLocation)),
                ('order', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('dateUpdated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('order', models.PositiveIntegerField(default=0)),
                ('smallDescription', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('video', models.FileField(upload_to=portfolio.models.videoLocation)),
                ('order', models.PositiveIntegerField(default=0)),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'dateCreated'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.ProjectCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.LinkCategory'),
        ),
    ]
