# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20160120_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=portfolio.models.imageLocation),
        ),
    ]
