# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20160120_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
