# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20160121_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='imgType',
            field=models.CharField(choices=[('mni', 'Main Image'), ('gal', 'Gallery')], default='gal', max_length=3),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
