# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20160121_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='links',
        ),
    ]
