# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
