# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20160121_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
