# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:28
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20160121_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
