# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20160121_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='project', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.imageLocation),
        ),
    ]
