# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 01:23
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20160122_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=portfolio.models.imageLocation),
        ),
    ]
