# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('ligoj', '0002_auto_20170102_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ligoj.Link')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligoj_taggedlink_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='ligoj.TaggedLink', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
