# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-03 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligoj', '0003_auto_20170102_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='no name', editable=False, max_length=140),
        ),
    ]
