# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-04 08:58
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ligoj', '0004_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ligoj.TaggedLink', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
