# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligoj', '0007_auto_20170104_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(default='no name', max_length=140),
        ),
    ]
