# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-06 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligoj', '0008_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(default='no name', editable=False, max_length=140),
        ),
    ]
