# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('publish', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(editable=False)),
                ('text', models.TextField()),
                ('cv', models.ManyToManyField(to='cv.CV')),
            ],
            options={
                'ordering': ['pk', 'name'],
            },
        ),
    ]
