# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cv',
        ),
        migrations.AddField(
            model_name='cv',
            name='sections',
            field=models.ManyToManyField(to='cv.Section'),
        ),
    ]
