# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20170730_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.CV')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Section')),
            ],
        ),
    ]
