# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_sectionorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='sections',
        ),
        migrations.AddField(
            model_name='cv',
            name='sections',
            field=models.ManyToManyField(related_name='sections', through='cv.SectionOrder', to='cv.Section'),
        ),
    ]
