# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20170730_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='cv',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='dateUpdated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='cv',
            name='sections',
            field=models.ManyToManyField(through='cv.SectionOrder', to='cv.Section'),
        ),
    ]
